name: legend-engine # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A 2D text based game engine written in Rust  # 79 char long summary
description: |
  The legend engine is a 2D text based game engine written in Rust.
  

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  legend:
    # See 'snapcraft plugins'
    plugin: rust
    source: .
    build-packages:
      - libncurses5-dev

apps:
 legend:
  command: legend
